{{- if .Values.prometheus.enabled }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
{{- fail "The cluster does not support the required API resource `monitoring.coreos.com/v1/ServiceMonitor`." }}
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "chart.fullname" . }}-prometheus
spec:
  serviceAccountName: {{ include "chart.fullname" . }}-prometheus
  # Associated ServiceMonitor selector
  serviceMonitorSelector:
    # Need to match the label in ServiceMonitor
    # https://github.com/kubernetes-sigs/jobset/blob/main/config/components/prometheus/monitor.yaml#L7
    matchLabels:
      control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 6 }}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
{{- end }}
