{{- if .Values.prometheus.enabled }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
{{- fail "The cluster does not support the required API resource `monitoring.coreos.com/v1/ServiceMonitor`." }}
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager-metrics-monitor
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: llmaz
    app.kubernetes.io/part-of: llmaz
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
    {{- include "chart.selectorLabels" . | nindent 6 }}
{{- end }}
