{{- if .Values.backendRuntime.enabled -}}
apiVersion: inference.llmaz.io/v1alpha1
kind: BackendRuntime
metadata:
  labels:
    app.kubernetes.io/name: backendruntime
    app.kubernetes.io/part-of: llmaz
    app.kubernetes.io/created-by: llmaz
  name: tgi
spec:
  image: {{ .Values.backendRuntime.tgi.image.repository }}
  version: {{ .Values.backendRuntime.tgi.image.tag }}
  lifecycle:
    preStop:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            while true; do
              RUNNING=$(curl -s http://localhost:8080/metrics | grep 'tgi_batch_current_size' | grep -v '#' | awk '{print $2}')
              WAITING=$(curl -s http://localhost:8080/metrics | grep 'tgi_queue_size' | grep -v '#' | awk '{print $2}')
              if [ "$RUNNING" = "0" ] && [ "$WAITING" = "0" ]; then
                echo "Terminating: No active or waiting requests, safe to terminate" >> /proc/1/fd/1
                exit 0
              else
                echo "Terminating: Running: $RUNNING, Waiting: $WAITING" >> /proc/1/fd/1
                sleep 5
              fi
            done
  # Do not edit the preset argument name unless you know what you're doing.
  # Free to add more arguments with your requirements.
  recommendedConfigs:
    - name: default
      args:
        - --model-id
        - "{{`{{ .ModelPath }}`}}"
        - --port
        - "8080"
      resources:
        requests:
          cpu: 4
          memory: 8Gi
        limits:
          cpu: 4
          memory: 8Gi
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    httpGet:
      path: /health
      port: 8080
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 3
    httpGet:
      path: /health
      port: 8080
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3
    httpGet:
      path: /health
      port: 8080
{{- end }}
