{{- if .Values.envoyAIGateway.enabled -}}
# source : https://github.com/envoyproxy/ai-gateway/blob/main/examples/basic/basic.yaml

# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-ai-gateway-basic
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-ai-gateway-basic
  namespace: default
spec:
  gatewayClassName: envoy-ai-gateway-basic
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-basic
  namespace: default
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: envoy-ai-gateway-basic
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    # - matches:
    #     - headers:
    #         - type: Exact
    #           name: x-ai-eg-model
    #           value: some-cool-self-hosted-model
    #   backendRefs:
    #     - name: envoy-ai-gateway-basic-testupstream
# Below is a testupstream service that can be used to test the AI Gateway
# ---
# apiVersion: aigateway.envoyproxy.io/v1alpha1
# kind: AIServiceBackend
# metadata:
#   name: envoy-ai-gateway-basic-testupstream
#   namespace: default
# spec:
#   schema:
#     name: OpenAI
#   backendRef:
#     name: envoy-ai-gateway-basic-testupstream
#     kind: Service
#     port: 80
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: envoy-ai-gateway-basic-testupstream
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: envoy-ai-gateway-basic-testupstream
#   template:
#     metadata:
#       labels:
#         app: envoy-ai-gateway-basic-testupstream
#     spec:
#       containers:
#         - name: testupstream
#           image: docker.io/envoyproxy/ai-gateway-testupstream:latest
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 8080
#           env:
#             - name: TESTUPSTREAM_ID
#               value: test
#           readinessProbe:
#             httpGet:
#               path: /health
#               port: 8080
#             initialDelaySeconds: 1
#             periodSeconds: 1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: envoy-ai-gateway-basic-testupstream
#   namespace: default
# spec:
#   selector:
#     app: envoy-ai-gateway-basic-testupstream
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: ClusterIP
{{- end }}
