/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	inferencev1alpha1 "github.com/inftyai/llmaz/api/inference/v1alpha1"
	applyconfigurationinferencev1alpha1 "github.com/inftyai/llmaz/client-go/applyconfiguration/inference/v1alpha1"
	scheme "github.com/inftyai/llmaz/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PlaygroundsGetter has a method to return a PlaygroundInterface.
// A group's client should implement this interface.
type PlaygroundsGetter interface {
	Playgrounds(namespace string) PlaygroundInterface
}

// PlaygroundInterface has methods to work with Playground resources.
type PlaygroundInterface interface {
	Create(ctx context.Context, playground *inferencev1alpha1.Playground, opts v1.CreateOptions) (*inferencev1alpha1.Playground, error)
	Update(ctx context.Context, playground *inferencev1alpha1.Playground, opts v1.UpdateOptions) (*inferencev1alpha1.Playground, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, playground *inferencev1alpha1.Playground, opts v1.UpdateOptions) (*inferencev1alpha1.Playground, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*inferencev1alpha1.Playground, error)
	List(ctx context.Context, opts v1.ListOptions) (*inferencev1alpha1.PlaygroundList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *inferencev1alpha1.Playground, err error)
	Apply(ctx context.Context, playground *applyconfigurationinferencev1alpha1.PlaygroundApplyConfiguration, opts v1.ApplyOptions) (result *inferencev1alpha1.Playground, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, playground *applyconfigurationinferencev1alpha1.PlaygroundApplyConfiguration, opts v1.ApplyOptions) (result *inferencev1alpha1.Playground, err error)
	PlaygroundExpansion
}

// playgrounds implements PlaygroundInterface
type playgrounds struct {
	*gentype.ClientWithListAndApply[*inferencev1alpha1.Playground, *inferencev1alpha1.PlaygroundList, *applyconfigurationinferencev1alpha1.PlaygroundApplyConfiguration]
}

// newPlaygrounds returns a Playgrounds
func newPlaygrounds(c *InferenceV1alpha1Client, namespace string) *playgrounds {
	return &playgrounds{
		gentype.NewClientWithListAndApply[*inferencev1alpha1.Playground, *inferencev1alpha1.PlaygroundList, *applyconfigurationinferencev1alpha1.PlaygroundApplyConfiguration](
			"playgrounds",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *inferencev1alpha1.Playground { return &inferencev1alpha1.Playground{} },
			func() *inferencev1alpha1.PlaygroundList { return &inferencev1alpha1.PlaygroundList{} },
		),
	}
}
