/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "inftyai.com/llmaz/api/inference/v1alpha1"
	inferencev1alpha1 "inftyai.com/llmaz/client-go/applyconfiguration/inference/v1alpha1"
	scheme "inftyai.com/llmaz/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PlaygroundsGetter has a method to return a PlaygroundInterface.
// A group's client should implement this interface.
type PlaygroundsGetter interface {
	Playgrounds(namespace string) PlaygroundInterface
}

// PlaygroundInterface has methods to work with Playground resources.
type PlaygroundInterface interface {
	Create(ctx context.Context, playground *v1alpha1.Playground, opts v1.CreateOptions) (*v1alpha1.Playground, error)
	Update(ctx context.Context, playground *v1alpha1.Playground, opts v1.UpdateOptions) (*v1alpha1.Playground, error)
	UpdateStatus(ctx context.Context, playground *v1alpha1.Playground, opts v1.UpdateOptions) (*v1alpha1.Playground, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Playground, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PlaygroundList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Playground, err error)
	Apply(ctx context.Context, playground *inferencev1alpha1.PlaygroundApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Playground, err error)
	ApplyStatus(ctx context.Context, playground *inferencev1alpha1.PlaygroundApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Playground, err error)
	PlaygroundExpansion
}

// playgrounds implements PlaygroundInterface
type playgrounds struct {
	client rest.Interface
	ns     string
}

// newPlaygrounds returns a Playgrounds
func newPlaygrounds(c *InferenceV1alpha1Client, namespace string) *playgrounds {
	return &playgrounds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the playground, and returns the corresponding playground object, and an error if there is any.
func (c *playgrounds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Playground, err error) {
	result = &v1alpha1.Playground{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("playgrounds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Playgrounds that match those selectors.
func (c *playgrounds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PlaygroundList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PlaygroundList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("playgrounds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested playgrounds.
func (c *playgrounds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("playgrounds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a playground and creates it.  Returns the server's representation of the playground, and an error, if there is any.
func (c *playgrounds) Create(ctx context.Context, playground *v1alpha1.Playground, opts v1.CreateOptions) (result *v1alpha1.Playground, err error) {
	result = &v1alpha1.Playground{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("playgrounds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(playground).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a playground and updates it. Returns the server's representation of the playground, and an error, if there is any.
func (c *playgrounds) Update(ctx context.Context, playground *v1alpha1.Playground, opts v1.UpdateOptions) (result *v1alpha1.Playground, err error) {
	result = &v1alpha1.Playground{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("playgrounds").
		Name(playground.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(playground).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *playgrounds) UpdateStatus(ctx context.Context, playground *v1alpha1.Playground, opts v1.UpdateOptions) (result *v1alpha1.Playground, err error) {
	result = &v1alpha1.Playground{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("playgrounds").
		Name(playground.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(playground).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the playground and deletes it. Returns an error if one occurs.
func (c *playgrounds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("playgrounds").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *playgrounds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("playgrounds").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched playground.
func (c *playgrounds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Playground, err error) {
	result = &v1alpha1.Playground{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("playgrounds").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied playground.
func (c *playgrounds) Apply(ctx context.Context, playground *inferencev1alpha1.PlaygroundApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Playground, err error) {
	if playground == nil {
		return nil, fmt.Errorf("playground provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(playground)
	if err != nil {
		return nil, err
	}
	name := playground.Name
	if name == nil {
		return nil, fmt.Errorf("playground.Name must be provided to Apply")
	}
	result = &v1alpha1.Playground{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("playgrounds").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *playgrounds) ApplyStatus(ctx context.Context, playground *inferencev1alpha1.PlaygroundApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Playground, err error) {
	if playground == nil {
		return nil, fmt.Errorf("playground provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(playground)
	if err != nil {
		return nil, err
	}

	name := playground.Name
	if name == nil {
		return nil, fmt.Errorf("playground.Name must be provided to Apply")
	}

	result = &v1alpha1.Playground{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("playgrounds").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
