FROM python:3.10-alpine AS builder

WORKDIR /workspace

COPY pyproject.toml poetry.lock ./
ENV POETRY_VIRTUALENVS_CREATE=false

RUN apk add --no-cache \
    build-base \
    libffi-dev \
    openssl-dev \
    py3-pip \
    bash

RUN pip install --no-cache-dir poetry==1.8.4 && poetry install --no-dev


FROM python:3.10-alpine

WORKDIR /workspace

RUN apk add --no-cache \
    bash

COPY llmaz/ llmaz/
COPY --from=builder /workspace /workspace
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin/ /usr/local/bin/

RUN mv llmaz/main.py main.py

CMD ["python", "main.py"]
