FROM python:3.9-alpine

WORKDIR /workspace

RUN apk add --no-cache \
    build-base \
    libffi-dev \
    openssl-dev \
    py3-pip \
    bash \
    git

RUN pip install --no-cache-dir poetry

RUN poetry config virtualenvs.create false
COPY pyproject.toml poetry.lock .
RUN poetry install --no-dev

COPY pkg/loader/ loader/

# Two args will be accepted here.
CMD ["python", "loader/loader.py"]
