apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-global-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  config.data: {{ .Values.globalConfig.configData | toYaml | indent 1 }}
