/*
Copyright 2025 The InftyAI Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiinferencev1alpha1 "github.com/inftyai/llmaz/api/inference/v1alpha1"
	versioned "github.com/inftyai/llmaz/client-go/clientset/versioned"
	internalinterfaces "github.com/inftyai/llmaz/client-go/informers/externalversions/internalinterfaces"
	inferencev1alpha1 "github.com/inftyai/llmaz/client-go/listers/inference/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PlaygroundInformer provides access to a shared informer and lister for
// Playgrounds.
type PlaygroundInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() inferencev1alpha1.PlaygroundLister
}

type playgroundInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPlaygroundInformer constructs a new informer for Playground type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPlaygroundInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPlaygroundInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPlaygroundInformer constructs a new informer for Playground type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPlaygroundInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InferenceV1alpha1().Playgrounds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InferenceV1alpha1().Playgrounds(namespace).Watch(context.TODO(), options)
			},
		},
		&apiinferencev1alpha1.Playground{},
		resyncPeriod,
		indexers,
	)
}

func (f *playgroundInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPlaygroundInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *playgroundInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiinferencev1alpha1.Playground{}, f.defaultInformer)
}

func (f *playgroundInformer) Lister() inferencev1alpha1.PlaygroundLister {
	return inferencev1alpha1.NewPlaygroundLister(f.Informer().GetIndexer())
}
