/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "inftyai.com/llmaz/api/core/v1alpha1"
	corev1alpha1 "inftyai.com/llmaz/client-go/applyconfiguration/core/v1alpha1"
	scheme "inftyai.com/llmaz/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OpenModelsGetter has a method to return a OpenModelInterface.
// A group's client should implement this interface.
type OpenModelsGetter interface {
	OpenModels(namespace string) OpenModelInterface
}

// OpenModelInterface has methods to work with OpenModel resources.
type OpenModelInterface interface {
	Create(ctx context.Context, openModel *v1alpha1.OpenModel, opts v1.CreateOptions) (*v1alpha1.OpenModel, error)
	Update(ctx context.Context, openModel *v1alpha1.OpenModel, opts v1.UpdateOptions) (*v1alpha1.OpenModel, error)
	UpdateStatus(ctx context.Context, openModel *v1alpha1.OpenModel, opts v1.UpdateOptions) (*v1alpha1.OpenModel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.OpenModel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.OpenModelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OpenModel, err error)
	Apply(ctx context.Context, openModel *corev1alpha1.OpenModelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OpenModel, err error)
	ApplyStatus(ctx context.Context, openModel *corev1alpha1.OpenModelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OpenModel, err error)
	OpenModelExpansion
}

// openModels implements OpenModelInterface
type openModels struct {
	client rest.Interface
	ns     string
}

// newOpenModels returns a OpenModels
func newOpenModels(c *LlmazV1alpha1Client, namespace string) *openModels {
	return &openModels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the openModel, and returns the corresponding openModel object, and an error if there is any.
func (c *openModels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OpenModel, err error) {
	result = &v1alpha1.OpenModel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("openmodels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OpenModels that match those selectors.
func (c *openModels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OpenModelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OpenModelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("openmodels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested openModels.
func (c *openModels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("openmodels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a openModel and creates it.  Returns the server's representation of the openModel, and an error, if there is any.
func (c *openModels) Create(ctx context.Context, openModel *v1alpha1.OpenModel, opts v1.CreateOptions) (result *v1alpha1.OpenModel, err error) {
	result = &v1alpha1.OpenModel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("openmodels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(openModel).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a openModel and updates it. Returns the server's representation of the openModel, and an error, if there is any.
func (c *openModels) Update(ctx context.Context, openModel *v1alpha1.OpenModel, opts v1.UpdateOptions) (result *v1alpha1.OpenModel, err error) {
	result = &v1alpha1.OpenModel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("openmodels").
		Name(openModel.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(openModel).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *openModels) UpdateStatus(ctx context.Context, openModel *v1alpha1.OpenModel, opts v1.UpdateOptions) (result *v1alpha1.OpenModel, err error) {
	result = &v1alpha1.OpenModel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("openmodels").
		Name(openModel.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(openModel).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the openModel and deletes it. Returns an error if one occurs.
func (c *openModels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("openmodels").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *openModels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("openmodels").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched openModel.
func (c *openModels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OpenModel, err error) {
	result = &v1alpha1.OpenModel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("openmodels").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied openModel.
func (c *openModels) Apply(ctx context.Context, openModel *corev1alpha1.OpenModelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OpenModel, err error) {
	if openModel == nil {
		return nil, fmt.Errorf("openModel provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(openModel)
	if err != nil {
		return nil, err
	}
	name := openModel.Name
	if name == nil {
		return nil, fmt.Errorf("openModel.Name must be provided to Apply")
	}
	result = &v1alpha1.OpenModel{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("openmodels").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *openModels) ApplyStatus(ctx context.Context, openModel *corev1alpha1.OpenModelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OpenModel, err error) {
	if openModel == nil {
		return nil, fmt.Errorf("openModel provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(openModel)
	if err != nil {
		return nil, err
	}

	name := openModel.Name
	if name == nil {
		return nil, fmt.Errorf("openModel.Name must be provided to Apply")
	}

	result = &v1alpha1.OpenModel{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("openmodels").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
