/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/inftyai/llmaz/api/core/v1alpha1"
	applyconfigurationcorev1alpha1 "github.com/inftyai/llmaz/client-go/applyconfiguration/core/v1alpha1"
	scheme "github.com/inftyai/llmaz/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OpenModelsGetter has a method to return a OpenModelInterface.
// A group's client should implement this interface.
type OpenModelsGetter interface {
	OpenModels(namespace string) OpenModelInterface
}

// OpenModelInterface has methods to work with OpenModel resources.
type OpenModelInterface interface {
	Create(ctx context.Context, openModel *corev1alpha1.OpenModel, opts v1.CreateOptions) (*corev1alpha1.OpenModel, error)
	Update(ctx context.Context, openModel *corev1alpha1.OpenModel, opts v1.UpdateOptions) (*corev1alpha1.OpenModel, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, openModel *corev1alpha1.OpenModel, opts v1.UpdateOptions) (*corev1alpha1.OpenModel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.OpenModel, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.OpenModelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.OpenModel, err error)
	Apply(ctx context.Context, openModel *applyconfigurationcorev1alpha1.OpenModelApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.OpenModel, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, openModel *applyconfigurationcorev1alpha1.OpenModelApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.OpenModel, err error)
	OpenModelExpansion
}

// openModels implements OpenModelInterface
type openModels struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.OpenModel, *corev1alpha1.OpenModelList, *applyconfigurationcorev1alpha1.OpenModelApplyConfiguration]
}

// newOpenModels returns a OpenModels
func newOpenModels(c *LlmazV1alpha1Client, namespace string) *openModels {
	return &openModels{
		gentype.NewClientWithListAndApply[*corev1alpha1.OpenModel, *corev1alpha1.OpenModelList, *applyconfigurationcorev1alpha1.OpenModelApplyConfiguration](
			"openmodels",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.OpenModel { return &corev1alpha1.OpenModel{} },
			func() *corev1alpha1.OpenModelList { return &corev1alpha1.OpenModelList{} },
		),
	}
}
