/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DataSourceApplyConfiguration represents an declarative configuration of the DataSource type for use
// with apply.
type DataSourceApplyConfiguration struct {
	ModelID  *string `json:"modelID,omitempty"`
	ModelHub *string `json:"modelHub,omitempty"`
}

// DataSourceApplyConfiguration constructs an declarative configuration of the DataSource type for use with
// apply.
func DataSource() *DataSourceApplyConfiguration {
	return &DataSourceApplyConfiguration{}
}

// WithModelID sets the ModelID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelID field is set to the value of the last call.
func (b *DataSourceApplyConfiguration) WithModelID(value string) *DataSourceApplyConfiguration {
	b.ModelID = &value
	return b
}

// WithModelHub sets the ModelHub field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelHub field is set to the value of the last call.
func (b *DataSourceApplyConfiguration) WithModelHub(value string) *DataSourceApplyConfiguration {
	b.ModelHub = &value
	return b
}
