/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/inftyai/llmaz/api/core/v1alpha1"
)

// ModelSourceApplyConfiguration represents a declarative configuration of the ModelSource type for use
// with apply.
type ModelSourceApplyConfiguration struct {
	ModelHub *ModelHubApplyConfiguration `json:"modelHub,omitempty"`
	URI      *corev1alpha1.URIProtocol   `json:"uri,omitempty"`
}

// ModelSourceApplyConfiguration constructs a declarative configuration of the ModelSource type for use with
// apply.
func ModelSource() *ModelSourceApplyConfiguration {
	return &ModelSourceApplyConfiguration{}
}

// WithModelHub sets the ModelHub field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelHub field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithModelHub(value *ModelHubApplyConfiguration) *ModelSourceApplyConfiguration {
	b.ModelHub = value
	return b
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithURI(value corev1alpha1.URIProtocol) *ModelSourceApplyConfiguration {
	b.URI = &value
	return b
}
