/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "inftyai.com/llmaz/api/inference/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PlaygroundLister helps list Playgrounds.
// All objects returned here must be treated as read-only.
type PlaygroundLister interface {
	// List lists all Playgrounds in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Playground, err error)
	// Playgrounds returns an object that can list and get Playgrounds.
	Playgrounds(namespace string) PlaygroundNamespaceLister
	PlaygroundListerExpansion
}

// playgroundLister implements the PlaygroundLister interface.
type playgroundLister struct {
	indexer cache.Indexer
}

// NewPlaygroundLister returns a new PlaygroundLister.
func NewPlaygroundLister(indexer cache.Indexer) PlaygroundLister {
	return &playgroundLister{indexer: indexer}
}

// List lists all Playgrounds in the indexer.
func (s *playgroundLister) List(selector labels.Selector) (ret []*v1alpha1.Playground, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Playground))
	})
	return ret, err
}

// Playgrounds returns an object that can list and get Playgrounds.
func (s *playgroundLister) Playgrounds(namespace string) PlaygroundNamespaceLister {
	return playgroundNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// PlaygroundNamespaceLister helps list and get Playgrounds.
// All objects returned here must be treated as read-only.
type PlaygroundNamespaceLister interface {
	// List lists all Playgrounds in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Playground, err error)
	// Get retrieves the Playground from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Playground, error)
	PlaygroundNamespaceListerExpansion
}

// playgroundNamespaceLister implements the PlaygroundNamespaceLister
// interface.
type playgroundNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Playgrounds in the indexer for a given namespace.
func (s playgroundNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.Playground, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Playground))
	})
	return ret, err
}

// Get retrieves the Playground from the indexer for a given namespace and name.
func (s playgroundNamespaceLister) Get(name string) (*v1alpha1.Playground, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("playground"), name)
	}
	return obj.(*v1alpha1.Playground), nil
}
