apiVersion: llmaz.io/v1alpha1
kind: OpenModel
metadata:
  name: qwen2-0--5b-instruct
spec:
  familyName: qwen2
  source:
    # download the model to the host ahead.
    uri: host:///workspace/Qwen2-0.5B-Instruct
  inferenceConfig:
    flavors:
      - name: t4 # GPU type
        limits:
          nvidia.com/gpu: 1
---
apiVersion: inference.llmaz.io/v1alpha1
kind: Playground
metadata:
  name: qwen2-0--5b-instruct
spec:
  replicas: 1
  modelClaim:
    modelName: qwen2-0--5b-instruct
