name: Event Workflow

env:
  GH_DEBUG: api

on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  event-handler:
    uses: kerthcet/github-workflow-as-kube/.github/workflows/workflow-as-kubernetes.yaml@v0.1.10
    secrets:
      AGENT_TOKEN: ${{ secrets.AGENT_TOKEN }}
