/*
Copyright 2024 The InftyAI Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PlaygroundStatusApplyConfiguration represents a declarative configuration of the PlaygroundStatus type for use
// with apply.
type PlaygroundStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	Replicas   *int32                           `json:"replicas,omitempty"`
	Selector   *string                          `json:"selector,omitempty"`
}

// PlaygroundStatusApplyConfiguration constructs a declarative configuration of the PlaygroundStatus type for use with
// apply.
func PlaygroundStatus() *PlaygroundStatusApplyConfiguration {
	return &PlaygroundStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PlaygroundStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *PlaygroundStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *PlaygroundStatusApplyConfiguration) WithReplicas(value int32) *PlaygroundStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *PlaygroundStatusApplyConfiguration) WithSelector(value string) *PlaygroundStatusApplyConfiguration {
	b.Selector = &value
	return b
}
